### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by 10212** [boschresearch/incSIM#1]
$ ./waf -v and main log as follow:
Waf: Leaving directory `/ndn/ndnSIM/ns-3/build'
Build failed
 -> task in 'ns3-incSIM' failed with exit status 1: 
	{task 140593871105600: cxx inc-data-producer.cpp -> inc-data-producer.cpp.1.o}
-> task in 'ns3-incSIM' failed with exit status 1: 
	{task 140593871105824: cxx NFN-producer-app.cpp -> NFN-producer-app.cpp.1.o}

../src/incSIM/apps/inc_compute_node_apps/inc_compute_app/inc-data-producer.cpp: In member function ‘virtual void ns3::ndn::inc::DataProducer::OnInterest(std::shared_ptr<const ndn::Interest>)’:
../src/incSIM/apps/inc_compute_node_apps/inc_compute_app/inc-data-producer.cpp:124:3: error: ‘Signature’ was not declared in this scope; did you mean ‘m_signature’?
  124 |   Signature signature;
      |   ^~~~~~~~~
      |   m_signature
... ...
../src/incSIM/apps/inc_compute_node_apps/inc_compute_app/NFN-producer-app.cpp: In member function ‘std::shared_ptr<ndn::Data> ns3::ndn::inc::NfnProducerApp::PrepareDataPacket(ndn::Name, uint32_t, ns3::Time)’:
../src/incSIM/apps/inc_compute_node_apps/inc_compute_app/NFN-producer-app.cpp:311:3: error: ‘Signature’ was not declared in this scope; did you mean ‘m_signature’?
  311 |   Signature signature;
      |   ^~~~~~~~~
      |   m_signature
......
../src/incSIM/utils/topology/inc-annotated-topology-reader.cpp: In member function ‘std::pair<ns3::NodeContainer, ns3::NodeContainer> ns3::ndn::inc::IncNdnAnnotatedTopologyReader::ReadTopology()’:
../src/incSIM/utils/topology/inc-annotated-topology-reader.cpp:551:37: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  551 |                   for (int i = 0; i < inputs.size (); i++)
      |                                   ~~^~~~~~~~~~~~~~~~

**Comment by UthraAmbalavanan** [comment]
Please use ndnSIM v2.8 to resolve this issue. The latest version (ndnSIM V2.9) is not directly compatible due to the signature updates in v2.9.
